### ISSUE TITLE
Peer dependency error with plugin

### ISSUE THREAD

**Issue by brycewray** [11ty/eleventy-dev-server#5]
Mentioning to you (and will do so in the affected plugin, too) only because it may be that other plugins will be similarly affected, but 2.0.0-canary.1 crashed on launch with the following (cc @KyleMit):

```bash
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: eleventy_site@undefined
npm WARN Found: @11ty/eleventy@1.0.0
npm WARN node_modules/@11ty/eleventy
npm WARN   peer @11ty/eleventy@">=0.10.0-beta.1" from eleventy-plugin-embed-tweet@0.3.1
npm WARN   node_modules/eleventy-plugin-embed-tweet
npm WARN     dev eleventy-plugin-embed-tweet@"^0.3.1" from the root project
npm WARN   1 more (the root project)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @11ty/eleventy@">=0.10.0-beta.1" from eleventy-plugin-embed-tweet@0.3.1
npm WARN node_modules/eleventy-plugin-embed-tweet
npm WARN   dev eleventy-plugin-embed-tweet@"^0.3.1" from the root project
```

**Comment by KyleMit** [comment]
The relevants bits from the plugin are the [peer dependency in the `package.config`](https://github.com/KyleMit/eleventy-plugin-embed-tweet/blob/main/package.json#L29):

```json
"peerDependencies": {
    "@11ty/eleventy": ">=0.10.0-beta.1"
},
```

I need to drill into why `2.0.0-canary.1` does not satisfy `>=0.10.0-beta.1`

**Comment by KyleMit** [comment]
There's a super helpful [semver calculator](https://semver.npmjs.com/), but pre-releases seem brittle.

I want to support _everything_ past `0.10.0-beta.1`, but the simpelest string I can get to work is this:

```none
>0.10.0-beta  || >1.0.0-canary || >1.0.0-beta || >=1.0.1-canary || >=2.0.0-canary
````

And it still hits some edge cases

![image](https://user-images.githubusercontent.com/4307307/157536587-f6b5e3e2-6faf-4e42-af96-4f05186e58c1.png)

Since there are so many pre-releases and none of them really need to break, I might just remove the peer dependency check altogether?

**Comment by zachleat** [comment]
Hey y’all—I’ve solved this in Eleventy core. Check out this pattern to use instead of `peerDependencies`:

https://github.com/11ty/eleventy-plugin-syntaxhighlight/blob/23761d7fd54de0312040520175959327b1a0ab9b/package.json#L36-L38

https://github.com/11ty/eleventy-plugin-syntaxhighlight/blob/23761d7fd54de0312040520175959327b1a0ab9b/.eleventy.js#L12-L16

https://github.com/11ty/eleventy/blob/827ec845c83371343d7e6ca63bf575dd7ee9192f/src/UserConfig.js#L89-L99

The `versionCheck` configuration API method has been in place for a long time (I see it in v0.3.2 https://github.com/11ty/eleventy/blob/v0.3.2/src/UserConfig.js) but was only _recently_ modified to include prereleases (as of 1.0).

Read more at https://github.com/11ty/eleventy/issues/2001

**Comment by zachleat** [comment]
Going to close this one—sorry!

Per my comment above, I’d recommend using the pattern above to warn about dependency mismatches in Eleventy. You _may_ want to open another issue over at `eleventy-plugin-embed-tweet` for this one.

I created https://github.com/11ty/eleventy/issues/2269 to add some additional official docs for plugin authoring best practices

**Comment by brycewray** [comment]
> Going to close this one—sorry!
> 
> Per my comment above, I’d recommend using the pattern above to warn about dependency mismatches in Eleventy. You _may_ want to open another issue over at `eleventy-plugin-embed-tweet` for this one.

Did, indeed. TY as always, sir.
